apiVersion: apps/v1
kind: Deployment
metadata:
  name: iptables-agent
  labels:
    app: iptables-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iptables-agent
  template:
    metadata:
      labels:
        app: iptables-agent
    spec:
      # hostPID: true  # Descomenta si necesitas acceso a los procesos del host (opcional)
      containers:
        - name: iptables-agent
          image: harbor.petru.com/1prueba/iptables-agent:latest
          securityContext:
            privileged: true
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-controller-0.kafka-controller-headless.default.svc.cluster.local:9092"
            - name: KAFKA_TOPIC
              value: "firewall-events"
            - name: KAFKA_GROUP_ID
              value: "iptables-agent-group"
