apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: firewall-webhook-es
  namespace: argo-events
spec:
  service:
    ports:
      - port: 12000
  webhook:
    firewall:
      port: "12000"
      endpoint: "/firewall-hook"
      method: "POST"
