apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: firewall-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: firewall-dep
      eventSourceName: firewall-webhook-es
      eventName: firewall
  triggers:
    - template:
        name: kafka-trigger
        kafka:
          url: "PLAINTEXT://kafka.default.svc.cluster.local:9092"
          topic: "firewall-events"
          partition: 0
          payload:
            - src:
                dependencyName: firewall-dep
                dataKey: body
              dest: message
