apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: firewall-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: firewall-dep
      eventSourceName: firewall-webhook-es
      eventName: firewall
  triggers:
    - template:
        name: kafka-trigger
        kafka:
          url: "PLAINTEXT://kafka-controller-0.kafka-controller-headless.default.svc.cluster.local:9092"
          topic: "firewall-events"
          partition: 0
          dataTemplate:
            message: "{{ .Input | quote }}"
