apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: firewall-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: firewall-dep
      eventSourceName: firewall-webhook-es
      eventName: firewall  # coincide con la clave en "webhook: firewall:" del EventSource
  triggers:
    - template:
        name: kafka-trigger
        kafka:
          url: "PLAINTEXT://kafka-svc:9092"   # Ajustar a la dirección de tu broker Kafka en k8s
          topic: "firewall-events"
          partition: 0
          parameters:
            - src:
                dependencyName: firewall-dep
                dataKey: body
              dest: message
      # (opcional) si necesitas auth, ssl, etc. lo añades aquí
