apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: firewall-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: firewall-dep
      eventSourceName: firewall-webhook-es
      eventName: firewall
  triggers:
    - template:
        name: log-trigger
        log:
          intervalSeconds: 1
          payload:
            - src:
                dependencyName: firewall-dep
                dataKey: body
              dest: message
